<?php

/**
 * PluginaRichTextCkeditorSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaRichTextCkeditorSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaRichTextCkeditorSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaRichTextCkeditorSlot');
    }
}